# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car_name', models.CharField(max_length=200, verbose_name='Марка')),
                ('Man_date', models.DateTimeField(verbose_name='Дата производства')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('Last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('Car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BEApp.Car')),
            ],
        ),
    ]
